### ISSUE TITLE
remove merge conflicts label after merge conflicts resolved

### ISSUE THREAD

**Issue by iamrajiv** [mschilde/auto-label-merge-conflicts#34]
Is there a way to remove merge conflicts label automatically after merge conflicts resolved.

**Comment by jjlharrison** [comment]
You would need to run the action for all branches.

**Comment by Borda** [comment]
hi, we have run the action on every push, so whenever someone changes (eventually resolved conflict) it shall be triggered but in fact, no the label is still there...
https://github.com/PyTorchLightning/pytorch-lightning/blob/master/.github/workflows/events-recurrent.yml

**Comment by jvacek** [comment]
@Borda is this still the case? Should the issue be re-opened?
